---
strategy: polling
no_screen_padding: 'yes'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: latest
serverless_language: node
polling_url: "{% if feed == \"nos_algemeen\" %}\r\nhttps://feeds.nos.nl/nosnieuwsalgemeen\r\n{% elsif feed == \"nu_algemeen\" %}\r\nhttps://www.nu.nl/rss/Algemeen\r\n{% elsif feed == \"nu_binnenland\" %}\r\nhttps://www.nu.nl/rss/Binnenland\r\n{% elsif feed == \"nu_buitenland\" %}\r\nhttps://www.nu.nl/rss/Buitenland\r\n{% elsif feed == \"nu_economie\" %}\r\nhttps://www.nu.nl/rss/Economie\r\n{% elsif feed == \"nu_sport\" %}\r\nhttps://www.nu.nl/rss/Sport\r\n{% elsif feed == \"nu_tech\" %}\r\nhttps://www.nu.nl/rss/Tech\r\n{% elsif feed == \"rtl_algemeen\" %}\r\nhttps://www.rtlnieuws.nl/rss.xml\r\n{% elsif feed == \"ad_algemeen\" %}\r\nhttps://www.ad.nl/home/rss.xml\r\n{% elsif feed == \"ad_denhaag\" %}\r\nhttps://www.ad.nl/den-haag/rss.xml\r\n{% elsif feed == \"ad_rotterdam\" %}\r\nhttps://www.ad.nl/rotterdam/rss.xml\r\n{% elsif feed == \"ad_utrecht\" %}\r\nhttps://www.ad.nl/utrecht/rss.xml\r\n{% elsif feed == \"ad_amsterdam\" %}\r\nhttps://www.ad.nl/amsterdam/rss.xml\r\n{% elsif feed == \"ad_alphen\" %}\r\nhttps://www.ad.nl/alphen/rss.xml\r\n{% elsif feed == \"ad_amersfoort\" %}\r\nhttps://www.ad.nl/amersfoort/rss.xml\r\n{% elsif feed == \"ad_apeldoorn\" %}\r\nhttps://www.ad.nl/apeldoorn/rss.xml\r\n{% elsif feed == \"ad_arnhem\" %}\r\nhttps://www.ad.nl/arnhem/rss.xml\r\n{% elsif feed == \"ad_bergen\" %}\r\nhttps://www.ad.nl/bergen-op-zoom/rss.xml\r\n{% elsif feed == \"ad_breda\" %}\r\nhttps://www.ad.nl/breda/rss.xml\r\n{% elsif feed == \"ad_delft\" %}\r\nhttps://www.ad.nl/delft/rss.xml\r\n{% elsif feed == \"ad_denbosch\" %}\r\nhttps://www.ad.nl/den-bosch/rss.xml\r\n{% elsif feed == \"ad_dordrecht\" %}\r\nhttps://www.ad.nl/dordrecht/rss.xml\r\n{% elsif feed == \"ad_eindhoven\" %}\r\nhttps://www.ad.nl/eindhoven/rss.xml\r\n{% elsif feed == \"ad_enschede\" %}\r\nhttps://www.ad.nl/enschede/rss.xml\r\n{% elsif feed == \"ad_gouda\" %}\r\nhttps://www.ad.nl/gouda/rss.xml\r\n{% elsif feed == \"ad_groenehart\" %}\r\nhttps://www.ad.nl/groene-hart/rss.xml\r\n{% elsif feed == \"ad_hengelo\" %}\r\nhttps://www.ad.nl/hengelo/rss.xml\r\n{% elsif feed == \"ad_hoeksewaard\" %}\r\nhttps://www.ad.nl/hoekse-waard/rss.xml\r\n{% elsif feed == \"ad_nijmegen\" %}\r\nhttps://www.ad.nl/nijmegen/rss.xml\r\n{% elsif feed == \"ad_rivierenland\" %}\r\nhttps://www.ad.nl/rivierenland/rss.xml\r\n{% elsif feed == \"ad_roosendaal\" %}\r\nhttps://www.ad.nl/roosendaal/rss.xml\r\n{% elsif feed == \"ad_tilburg\" %}\r\nhttps://www.ad.nl/tilburg/rss.xml\r\n{% elsif feed == \"ad_voorneputten\" %}\r\nhttps://www.ad.nl/voorne-putten/rss.xml\r\n{% elsif feed == \"ad_westland\" %}\r\nhttps://www.ad.nl/westland/rss.xml\r\n{% elsif feed == \"ad_woerden\" %}\r\nhttps://www.ad.nl/woerden/rss.xml\r\n{% elsif feed == \"ad_zoetermeer\" %}\r\nhttps://www.ad.nl/zoetermeer/rss.xml\r\n{% elsif feed == \"ad_zwolle\" %}\r\nhttps://www.ad.nl/zwolle/rss.xml\r\n{% elsif feed == \"ad_binnenland\" %}\r\nhttps://www.ad.nl/binnenland/rss.xml\r\n{% elsif feed == \"ad_buitenland\" %}\r\nhttps://www.ad.nl/buitenland/rss.xml\r\n{% elsif feed == \"ad_sport\" %}\r\nhttps://www.ad.nl/sport/rss.xml\r\n{% elsif feed == \"ad_tech\" %}\r\nhttps://www.ad.nl/tech/rss.xml\r\n{% else %}\r\nhttps://feeds.nos.nl/nosnieuwsalgemeen\r\n{% endif %}"
polling_headers: ''
polling_body: ''
id: 206736
oauth_enabled: 'false'
oauth_pkce_enabled: 'no'
oauth_authorize_url: ''
oauth_token_url: ''
oauth_scopes: ''
oauth_scope_separator: ''
oauth_refresh_url: ''
oauth_auth_params: ''
oauth_token_headers: ''
oauth_token_site: ''
oauth_token_params: ''
oauth_token_request_auth_method: ''
oauth_body_format: ''
oauth_token_response_metadata: ''
oauth_authorization_method: ''
oauth_refresh_params: ''
oauth_token_field_name: ''
oauth_expiry_field_name: ''
oauth_expiry_strategy: ''
oauth_fixed_expiry_ms: ''
custom_fields:
- name: About this plugin
  keyname: author_bio
  field_type: author_bio
  description: Get the latest headlines from the NOS, RTL, AD or NU.nl, select a feed and get the latest news right on your TRMNL (in Dutch). <br><br> Questions or ideas or want an feed added? Email me or reach out on Discord at @Bas/@Bastronautica.
  email_address: trmnl@achtnegen.nl
- name: News feed
  description: Select the feed you would like to show
  keyname: feed
  field_type: select
  options:
  - NOS: nos_algemeen
  - RTL Nieuws: rtl_algemeen
  - NU.nl: nu_algemeen
  - NU.nl - Binnenland: nu_binnenland
  - NU.nl - Buitenland: nu_buitenland
  - NU.nl - Economie: nu_economie
  - NU.nl - Sport: nu_sport
  - NU.nl - Tech: nu_tech
  - AD: ad_algemeen
  - AD - Den Haag: ad_denhaag
  - AD - Rotterdam: ad_rotterdam
  - AD - Utrecht: ad_utrecht
  - AD - Amsterdam: ad_amsterdam
  - AD - Alphen: ad_alphen
  - AD - Amersfoort: ad_amersfoort
  - AD - Apeldoorn: ad_apeldoorn
  - AD - Arnhem: ad_arnhem
  - AD - Bergen op Zoom: ad_bergen
  - AD - Breda: ad_breda
  - AD - Delft: ad_delft
  - AD - Den Bosch: ad_denbosch
  - AD - Dordrecht: ad_dordrecht
  - AD - Eindhoven: ad_eindhoven
  - AD - Enschede: ad_enschede
  - AD - Gouda: ad_gouda
  - AD - Groene Hart: ad_groenehart
  - AD - Hengelo: ad_hengelo
  - AD - Hoekse Waard: ad_hoeksewaard
  - AD - Nijmegen: ad_nijmegen
  - AD - Rivierenland: ad_rivierenland
  - AD - Roosendaal: ad_roosendaal
  - AD - Tilburg: ad_tilburg
  - AD - Voorne-Putten: ad_voorneputten
  - AD - Westland: ad_westland
  - AD - Woerden: ad_woerden
  - AD - Zoetermeer: ad_zoetermeer
  - AD - Zwolle: ad_zwolle
  - AD - Binnenland: ad_binnenland
  - AD - Buitenland: ad_buitenland
  - AD - Sport: ad_sport
  - AD - Tech: ad_tech
  default: nos_algemeen
name: Laatste nieuws
description: NOS - RTL - AD - Nu.nl
refresh_interval: 30
